// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyClub.Scorer.Infrastructure.Persistence.DbContexts;

#nullable disable

namespace MyClub.Scorer.Infrastructure.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(ScorerDbContext))]
    [Migration("20250802044619_InitSchema")]
    partial class InitSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.6.25358.103")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyClub.Scorer.Domain.CompetitionAggregate.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompetitionType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Logo")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Competitions", (string)null);

                    b.HasDiscriminator<int>("CompetitionType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.CompetitionAggregate.Stadiums.Stadium", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ground")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Stadiums", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.CompetitionAggregate.Teams.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Managers", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.CompetitionAggregate.Teams.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.CompetitionAggregate.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AwayColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StadiumId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("StadiumId");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.MatchAggregate.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AfterExtraTime")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsNeutralStadium")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OriginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PostponedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("StadiumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StadiumId");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.MatchdayAggregate.Matchday", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPostponed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OriginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("_postponedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PostponedDate");

                    b.HasKey("Id");

                    b.ToTable("Matchdays", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.RoundAggregate.Fixture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Team1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("Fixtures", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.RoundAggregate.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AncestorRoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConsolation")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AncestorRoundId");

                    b.ToTable("Rounds", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.RoundAggregate.RoundStage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPostponed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OriginDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RoundId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("RoundStages", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.StageAggregate.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GroupStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupStageId");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.StageAggregate.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AncestorStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConsolation")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncestorStageId");

                    b.ToTable("Stages", (string)null);

                    b.HasDiscriminator<int>("StageType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.ChampionshipStageMatchday", b =>
                {
                    b.Property<Guid>("LeftId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ChampionshipStageId");

                    b.Property<Guid>("RightId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MatchdayId");

                    b.HasKey("LeftId", "RightId");

                    b.HasIndex("LeftId");

                    b.HasIndex("RightId");

                    b.ToTable("ChampionshipStageMatchdays", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.CupRound", b =>
                {
                    b.Property<Guid>("LeftId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CupId");

                    b.Property<Guid>("RightId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoundId");

                    b.HasKey("LeftId", "RightId");

                    b.HasIndex("LeftId");

                    b.HasIndex("RightId");

                    b.ToTable("CupRounds", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.GroupStageMatchday", b =>
                {
                    b.Property<Guid>("LeftId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GroupStageId");

                    b.Property<Guid>("RightId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MatchdayId");

                    b.HasKey("LeftId", "RightId");

                    b.HasIndex("LeftId");

                    b.HasIndex("RightId");

                    b.ToTable("GroupStageMatchdays", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.GroupTeam", b =>
                {
                    b.Property<Guid>("LeftId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GroupId");

                    b.Property<string>("Right")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Team");

                    b.HasKey("LeftId", "Right");

                    b.HasIndex("LeftId");

                    b.ToTable("GroupTeam");
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.KnockoutStageRound", b =>
                {
                    b.Property<Guid>("LeftId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("KnockoutStageId");

                    b.Property<Guid>("RightId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoundId");

                    b.HasKey("LeftId", "RightId");

                    b.HasIndex("LeftId");

                    b.HasIndex("RightId");

                    b.ToTable("KnockoutStageRounds", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.LeagueMatchday", b =>
                {
                    b.Property<Guid>("LeftId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LeagueId");

                    b.Property<Guid>("RightId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MatchdayId");

                    b.HasKey("LeftId", "RightId");

                    b.HasIndex("LeftId");

                    b.HasIndex("RightId");

                    b.ToTable("LeagueMatchdays", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.MatchdayMatch", b =>
                {
                    b.Property<Guid>("LeftId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MatchdayId");

                    b.Property<Guid>("RightId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MatchId");

                    b.HasKey("LeftId", "RightId");

                    b.HasIndex("LeftId");

                    b.HasIndex("RightId");

                    b.ToTable("MatchdayMatches", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.RoundStageMatch", b =>
                {
                    b.Property<Guid>("LeftId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoundStageId");

                    b.Property<Guid>("RightId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MatchId");

                    b.HasKey("LeftId", "RightId");

                    b.HasIndex("LeftId");

                    b.HasIndex("RightId");

                    b.ToTable("RoundStageMatches", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.RoundTeam", b =>
                {
                    b.Property<Guid>("LeftId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoundId");

                    b.Property<string>("Right")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Team");

                    b.HasKey("LeftId", "Right");

                    b.HasIndex("LeftId");

                    b.ToTable("RoundTeam");
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.StageTeam", b =>
                {
                    b.Property<Guid>("LeftId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StageId");

                    b.Property<string>("Right")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Team");

                    b.HasKey("LeftId", "Right");

                    b.HasIndex("LeftId");

                    b.ToTable("StageTeam");
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.TournamentStage", b =>
                {
                    b.Property<Guid>("LeftId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TournamentId");

                    b.Property<Guid>("RightId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StageId");

                    b.HasKey("LeftId", "RightId");

                    b.HasIndex("LeftId");

                    b.HasIndex("RightId");

                    b.ToTable("TournamentStages", (string)null);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.CompetitionAggregate.Cup", b =>
                {
                    b.HasBaseType("MyClub.Scorer.Domain.CompetitionAggregate.Competition");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.CompetitionAggregate.League", b =>
                {
                    b.HasBaseType("MyClub.Scorer.Domain.CompetitionAggregate.Competition");

                    b.Property<string>("PenaltyPoints")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.CompetitionAggregate.Tournament", b =>
                {
                    b.HasBaseType("MyClub.Scorer.Domain.CompetitionAggregate.Competition");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.StageAggregate.ChampionshipStage", b =>
                {
                    b.HasBaseType("MyClub.Scorer.Domain.StageAggregate.Stage");

                    b.Property<string>("PenaltyPoints")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PenaltyPoints");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.StageAggregate.GroupStage", b =>
                {
                    b.HasBaseType("MyClub.Scorer.Domain.StageAggregate.Stage");

                    b.Property<string>("PenaltyPoints")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PenaltyPoints");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.StageAggregate.KnockoutStage", b =>
                {
                    b.HasBaseType("MyClub.Scorer.Domain.StageAggregate.Stage");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.CompetitionAggregate.Competition", b =>
                {
                    b.OwnsOne("MyClub.Shared.Domain.ValueObjects.DisplayName", "DisplayName", b1 =>
                        {
                            b1.Property<Guid>("CompetitionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");

                            b1.Property<string>("ShortName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ShortName");

                            b1.HasKey("CompetitionId");

                            b1.ToTable("Competitions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompetitionId");
                        });

                    b.OwnsOne("MyClub.Scorer.Domain.CompetitionAggregate.Configurations.MatchFormat", "MatchFormat", b1 =>
                        {
                            b1.Property<Guid>("CompetitionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("NumberOfPenaltyShootouts")
                                .HasColumnType("int")
                                .HasColumnName("NumberOfPenaltyShootouts");

                            b1.HasKey("CompetitionId");

                            b1.ToTable("Competitions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompetitionId");

                            b1.OwnsOne("MyClub.Scorer.Domain.CompetitionAggregate.Configurations.PeriodFormat", "ExtraTime", b2 =>
                                {
                                    b2.Property<Guid>("MatchFormatCompetitionId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<TimeSpan>("Duration")
                                        .HasColumnType("time")
                                        .HasColumnName("ExtraTimeDuration");

                                    b2.Property<TimeSpan>("HalfTimeDuration")
                                        .HasColumnType("time")
                                        .HasColumnName("ExtraTimeHalfTimeDuration");

                                    b2.Property<int>("Number")
                                        .HasColumnType("int")
                                        .HasColumnName("ExtraTimeNumber");

                                    b2.HasKey("MatchFormatCompetitionId");

                                    b2.ToTable("Competitions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MatchFormatCompetitionId");
                                });

                            b1.OwnsOne("MyClub.Scorer.Domain.CompetitionAggregate.Configurations.PeriodFormat", "RegulationTime", b2 =>
                                {
                                    b2.Property<Guid>("MatchFormatCompetitionId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<TimeSpan>("Duration")
                                        .HasColumnType("time")
                                        .HasColumnName("RegulationTimeDuration");

                                    b2.Property<TimeSpan>("HalfTimeDuration")
                                        .HasColumnType("time")
                                        .HasColumnName("RegulationTimeHalfTimeDuration");

                                    b2.Property<int>("Number")
                                        .HasColumnType("int")
                                        .HasColumnName("RegulationTimeNumber");

                                    b2.HasKey("MatchFormatCompetitionId");

                                    b2.ToTable("Competitions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MatchFormatCompetitionId");
                                });

                            b1.Navigation("ExtraTime");

                            b1.Navigation("RegulationTime")
                                .IsRequired();
                        });

                    b.OwnsOne("MyClub.Scorer.Domain.CompetitionAggregate.Configurations.MatchRules", "MatchRules", b1 =>
                        {
                            b1.Property<Guid>("CompetitionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AllowedCards")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AllowedCards");

                            b1.HasKey("CompetitionId");

                            b1.ToTable("Competitions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompetitionId");
                        });

                    b.Navigation("DisplayName")
                        .IsRequired();

                    b.Navigation("MatchFormat")
                        .IsRequired();

                    b.Navigation("MatchRules")
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.CompetitionAggregate.Stadiums.Stadium", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.CompetitionAggregate.Competition", null)
                        .WithMany("Stadiums")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("MyClub.Shared.Domain.ValueObjects.DisplayName", "DisplayName", b1 =>
                        {
                            b1.Property<Guid>("StadiumId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");

                            b1.Property<string>("ShortName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ShortName");

                            b1.HasKey("StadiumId");

                            b1.ToTable("Stadiums", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StadiumId");
                        });

                    b.OwnsOne("MyNet.Utilities.Geography.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("StadiumId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Country");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("Street")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Street");

                            b1.HasKey("StadiumId");

                            b1.ToTable("Stadiums", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StadiumId");
                        });

                    b.Navigation("Address");

                    b.Navigation("DisplayName")
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.CompetitionAggregate.Teams.Manager", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.CompetitionAggregate.Teams.Team", null)
                        .WithMany("Staff")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.CompetitionAggregate.Teams.Player", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.CompetitionAggregate.Teams.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.CompetitionAggregate.Teams.Team", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.CompetitionAggregate.Competition", null)
                        .WithMany("Teams")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyClub.Scorer.Domain.CompetitionAggregate.Stadiums.Stadium", null)
                        .WithMany()
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("MyClub.Shared.Domain.ValueObjects.DisplayName", "DisplayName", b1 =>
                        {
                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");

                            b1.Property<string>("ShortName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ShortName");

                            b1.HasKey("TeamId");

                            b1.ToTable("Teams", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TeamId");
                        });

                    b.Navigation("DisplayName")
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.MatchAggregate.Match", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.CompetitionAggregate.Stadiums.Stadium", null)
                        .WithMany()
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("MyClub.Scorer.Domain.MatchAggregate.MatchOpponent", "Away", b1 =>
                        {
                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsWithdrawn")
                                .HasColumnType("bit")
                                .HasColumnName("AwayIsWithdrawn");

                            b1.Property<string>("Team")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AwayTeam");

                            b1.HasKey("MatchId");

                            b1.ToTable("Matches", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MatchId");

                            b1.OwnsMany("MyClub.Scorer.Domain.MatchAggregate.MatchEvents.Card", "_cards", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Color")
                                        .HasColumnType("int");

                                    b2.Property<string>("Description")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<int>("Infraction")
                                        .HasColumnType("int");

                                    b2.Property<Guid>("MatchId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int?>("Minute")
                                        .HasColumnType("int");

                                    b2.Property<Guid?>("PlayerId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MatchId");

                                    b2.ToTable("AwayCards", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MatchId");
                                });

                            b1.OwnsMany("MyClub.Scorer.Domain.MatchAggregate.MatchEvents.Goal", "_goals", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid?>("AssistId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("MatchId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int?>("Minute")
                                        .HasColumnType("int");

                                    b2.Property<Guid?>("ScorerId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MatchId");

                                    b2.ToTable("AwayGoals", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MatchId");
                                });

                            b1.OwnsMany("MyClub.Scorer.Domain.MatchAggregate.MatchEvents.PenaltyShootout", "_shootout", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("MatchId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Result")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<Guid?>("TakerId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MatchId");

                                    b2.ToTable("AwayPenaltyShootouts", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MatchId");
                                });

                            b1.Navigation("_cards");

                            b1.Navigation("_goals");

                            b1.Navigation("_shootout");
                        });

                    b.OwnsOne("MyClub.Scorer.Domain.CompetitionAggregate.Configurations.MatchFormat", "Format", b1 =>
                        {
                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("NumberOfPenaltyShootouts")
                                .HasColumnType("int")
                                .HasColumnName("NumberOfPenaltyShootouts");

                            b1.HasKey("MatchId");

                            b1.ToTable("Matches", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MatchId");

                            b1.OwnsOne("MyClub.Scorer.Domain.CompetitionAggregate.Configurations.PeriodFormat", "ExtraTime", b2 =>
                                {
                                    b2.Property<Guid>("MatchFormatMatchId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<TimeSpan>("Duration")
                                        .HasColumnType("time")
                                        .HasColumnName("ExtraTimeDuration");

                                    b2.Property<TimeSpan>("HalfTimeDuration")
                                        .HasColumnType("time")
                                        .HasColumnName("ExtraTimeHalfTimeDuration");

                                    b2.Property<int>("Number")
                                        .HasColumnType("int")
                                        .HasColumnName("ExtraTimeNumber");

                                    b2.HasKey("MatchFormatMatchId");

                                    b2.ToTable("Matches", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MatchFormatMatchId");
                                });

                            b1.OwnsOne("MyClub.Scorer.Domain.CompetitionAggregate.Configurations.PeriodFormat", "RegulationTime", b2 =>
                                {
                                    b2.Property<Guid>("MatchFormatMatchId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<TimeSpan>("Duration")
                                        .HasColumnType("time")
                                        .HasColumnName("RegulationTimeDuration");

                                    b2.Property<TimeSpan>("HalfTimeDuration")
                                        .HasColumnType("time")
                                        .HasColumnName("RegulationTimeHalfTimeDuration");

                                    b2.Property<int>("Number")
                                        .HasColumnType("int")
                                        .HasColumnName("RegulationTimeNumber");

                                    b2.HasKey("MatchFormatMatchId");

                                    b2.ToTable("Matches", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MatchFormatMatchId");
                                });

                            b1.Navigation("ExtraTime");

                            b1.Navigation("RegulationTime")
                                .IsRequired();
                        });

                    b.OwnsOne("MyClub.Scorer.Domain.MatchAggregate.MatchOpponent", "Home", b1 =>
                        {
                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsWithdrawn")
                                .HasColumnType("bit")
                                .HasColumnName("HomeIsWithdrawn");

                            b1.Property<string>("Team")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HomeTeam");

                            b1.HasKey("MatchId");

                            b1.ToTable("Matches", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MatchId");

                            b1.OwnsMany("MyClub.Scorer.Domain.MatchAggregate.MatchEvents.Card", "_cards", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Color")
                                        .HasColumnType("int");

                                    b2.Property<string>("Description")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<int>("Infraction")
                                        .HasColumnType("int");

                                    b2.Property<Guid>("MatchId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int?>("Minute")
                                        .HasColumnType("int");

                                    b2.Property<Guid?>("PlayerId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MatchId");

                                    b2.ToTable("HomeCards", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MatchId");
                                });

                            b1.OwnsMany("MyClub.Scorer.Domain.MatchAggregate.MatchEvents.Goal", "_goals", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid?>("AssistId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("MatchId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int?>("Minute")
                                        .HasColumnType("int");

                                    b2.Property<Guid?>("ScorerId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MatchId");

                                    b2.ToTable("HomeGoals", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MatchId");
                                });

                            b1.OwnsMany("MyClub.Scorer.Domain.MatchAggregate.MatchEvents.PenaltyShootout", "_shootout", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("MatchId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Result")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<Guid?>("TakerId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MatchId");

                                    b2.ToTable("HomePenaltyShootouts", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MatchId");
                                });

                            b1.Navigation("_cards");

                            b1.Navigation("_goals");

                            b1.Navigation("_shootout");
                        });

                    b.OwnsOne("MyClub.Scorer.Domain.CompetitionAggregate.Configurations.MatchRules", "Rules", b1 =>
                        {
                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AllowedCards")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AllowedCards");

                            b1.HasKey("MatchId");

                            b1.ToTable("Matches", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("Away")
                        .IsRequired();

                    b.Navigation("Format")
                        .IsRequired();

                    b.Navigation("Home")
                        .IsRequired();

                    b.Navigation("Rules")
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.MatchdayAggregate.Matchday", b =>
                {
                    b.OwnsOne("MyClub.Shared.Domain.ValueObjects.DisplayName", "DisplayName", b1 =>
                        {
                            b1.Property<Guid>("MatchdayId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");

                            b1.Property<string>("ShortName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ShortName");

                            b1.HasKey("MatchdayId");

                            b1.ToTable("Matchdays", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MatchdayId");
                        });

                    b.Navigation("DisplayName")
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.RoundAggregate.Fixture", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.RoundAggregate.Round", null)
                        .WithMany("Fixtures")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Fixtures_Rounds_RoundTempId");
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.RoundAggregate.Round", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.RoundAggregate.Round", null)
                        .WithMany()
                        .HasForeignKey("AncestorRoundId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("MyClub.Shared.Domain.ValueObjects.DisplayName", "DisplayName", b1 =>
                        {
                            b1.Property<Guid>("RoundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");

                            b1.Property<string>("ShortName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ShortName");

                            b1.HasKey("RoundId");

                            b1.ToTable("Rounds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoundId");
                        });

                    b.OwnsOne("MyClub.Scorer.Domain.CompetitionAggregate.Configurations.MatchRules", "Rules", b1 =>
                        {
                            b1.Property<Guid>("RoundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AllowedCards")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AllowedCards");

                            b1.HasKey("RoundId");

                            b1.ToTable("Rounds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoundId");
                        });

                    b.Navigation("DisplayName")
                        .IsRequired();

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.RoundAggregate.RoundStage", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.RoundAggregate.Round", null)
                        .WithMany("Stages")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_RoundStages_Rounds_RoundTempId1");

                    b.OwnsOne("MyClub.Shared.Domain.ValueObjects.DisplayName", "DisplayName", b1 =>
                        {
                            b1.Property<Guid>("RoundStageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");

                            b1.Property<string>("ShortName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ShortName");

                            b1.HasKey("RoundStageId");

                            b1.ToTable("RoundStages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoundStageId");
                        });

                    b.Navigation("DisplayName")
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.StageAggregate.Group", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.StageAggregate.GroupStage", null)
                        .WithMany("Groups")
                        .HasForeignKey("GroupStageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("MyClub.Shared.Domain.ValueObjects.DisplayName", "DisplayName", b1 =>
                        {
                            b1.Property<Guid>("GroupId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");

                            b1.Property<string>("ShortName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ShortName");

                            b1.HasKey("GroupId");

                            b1.ToTable("Groups", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GroupId");
                        });

                    b.Navigation("DisplayName")
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.StageAggregate.Stage", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.StageAggregate.Stage", null)
                        .WithMany()
                        .HasForeignKey("AncestorStageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("MyClub.Shared.Domain.ValueObjects.DisplayName", "DisplayName", b1 =>
                        {
                            b1.Property<Guid>("StageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");

                            b1.Property<string>("ShortName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ShortName");

                            b1.HasKey("StageId");

                            b1.ToTable("Stages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StageId");
                        });

                    b.OwnsOne("MyClub.Scorer.Domain.CompetitionAggregate.Configurations.MatchFormat", "MatchFormat", b1 =>
                        {
                            b1.Property<Guid>("StageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("NumberOfPenaltyShootouts")
                                .HasColumnType("int")
                                .HasColumnName("NumberOfPenaltyShootouts");

                            b1.HasKey("StageId");

                            b1.ToTable("Stages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StageId");

                            b1.OwnsOne("MyClub.Scorer.Domain.CompetitionAggregate.Configurations.PeriodFormat", "ExtraTime", b2 =>
                                {
                                    b2.Property<Guid>("MatchFormatStageId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<TimeSpan>("Duration")
                                        .HasColumnType("time")
                                        .HasColumnName("ExtraTimeDuration");

                                    b2.Property<TimeSpan>("HalfTimeDuration")
                                        .HasColumnType("time")
                                        .HasColumnName("ExtraTimeHalfTimeDuration");

                                    b2.Property<int>("Number")
                                        .HasColumnType("int")
                                        .HasColumnName("ExtraTimeNumber");

                                    b2.HasKey("MatchFormatStageId");

                                    b2.ToTable("Stages", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MatchFormatStageId");
                                });

                            b1.OwnsOne("MyClub.Scorer.Domain.CompetitionAggregate.Configurations.PeriodFormat", "RegulationTime", b2 =>
                                {
                                    b2.Property<Guid>("MatchFormatStageId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<TimeSpan>("Duration")
                                        .HasColumnType("time")
                                        .HasColumnName("RegulationTimeDuration");

                                    b2.Property<TimeSpan>("HalfTimeDuration")
                                        .HasColumnType("time")
                                        .HasColumnName("RegulationTimeHalfTimeDuration");

                                    b2.Property<int>("Number")
                                        .HasColumnType("int")
                                        .HasColumnName("RegulationTimeNumber");

                                    b2.HasKey("MatchFormatStageId");

                                    b2.ToTable("Stages", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MatchFormatStageId");
                                });

                            b1.Navigation("ExtraTime");

                            b1.Navigation("RegulationTime")
                                .IsRequired();
                        });

                    b.OwnsOne("MyClub.Scorer.Domain.CompetitionAggregate.Configurations.MatchRules", "Rules", b1 =>
                        {
                            b1.Property<Guid>("StageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AllowedCards")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AllowedCards");

                            b1.HasKey("StageId");

                            b1.ToTable("Stages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StageId");
                        });

                    b.Navigation("DisplayName")
                        .IsRequired();

                    b.Navigation("MatchFormat")
                        .IsRequired();

                    b.Navigation("Rules")
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.ChampionshipStageMatchday", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.StageAggregate.ChampionshipStage", "Left")
                        .WithMany()
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyClub.Scorer.Domain.MatchdayAggregate.Matchday", "Right")
                        .WithMany()
                        .HasForeignKey("RightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Left");

                    b.Navigation("Right");
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.CupRound", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.CompetitionAggregate.Cup", "Left")
                        .WithMany()
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyClub.Scorer.Domain.RoundAggregate.Round", "Right")
                        .WithMany()
                        .HasForeignKey("RightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Left");

                    b.Navigation("Right");
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.GroupStageMatchday", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.StageAggregate.GroupStage", "Left")
                        .WithMany()
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyClub.Scorer.Domain.MatchdayAggregate.Matchday", "Right")
                        .WithMany()
                        .HasForeignKey("RightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Left");

                    b.Navigation("Right");
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.GroupTeam", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.StageAggregate.Group", null)
                        .WithMany()
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.KnockoutStageRound", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.StageAggregate.KnockoutStage", "Left")
                        .WithMany()
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyClub.Scorer.Domain.RoundAggregate.Round", "Right")
                        .WithMany()
                        .HasForeignKey("RightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Left");

                    b.Navigation("Right");
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.LeagueMatchday", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.CompetitionAggregate.League", "Left")
                        .WithMany()
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyClub.Scorer.Domain.MatchdayAggregate.Matchday", "Right")
                        .WithMany()
                        .HasForeignKey("RightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Left");

                    b.Navigation("Right");
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.MatchdayMatch", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.MatchdayAggregate.Matchday", "Left")
                        .WithMany()
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyClub.Scorer.Domain.MatchAggregate.Match", "Right")
                        .WithMany()
                        .HasForeignKey("RightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Left");

                    b.Navigation("Right");
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.RoundStageMatch", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.RoundAggregate.RoundStage", "Left")
                        .WithMany()
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyClub.Scorer.Domain.MatchAggregate.Match", "Right")
                        .WithMany()
                        .HasForeignKey("RightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Left");

                    b.Navigation("Right");
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.RoundTeam", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.RoundAggregate.Round", null)
                        .WithMany()
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.StageTeam", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.StageAggregate.Stage", null)
                        .WithMany()
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.Scorer.Infrastructure.Persistence.JoinEntities.TournamentStage", b =>
                {
                    b.HasOne("MyClub.Scorer.Domain.CompetitionAggregate.Tournament", "Left")
                        .WithMany()
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyClub.Scorer.Domain.StageAggregate.Stage", "Right")
                        .WithMany()
                        .HasForeignKey("RightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Left");

                    b.Navigation("Right");
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.CompetitionAggregate.League", b =>
                {
                    b.OwnsMany("MyClub.Scorer.Domain.CompetitionAggregate.Configurations.StandingLabel", "Labels", b1 =>
                        {
                            b1.Property<Guid>("LeagueId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Color")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Order")
                                .HasColumnType("int");

                            b1.Property<string>("ShortName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("LeagueId", "Id");

                            b1.ToTable("LeagueStandingLabels", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LeagueId");

                            b1.OwnsOne("MyNet.Utilities.Sequences.Interval<int>", "Ranks", b2 =>
                                {
                                    b2.Property<Guid>("StandingLabelLeagueId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("StandingLabelId")
                                        .HasColumnType("int");

                                    b2.Property<int>("End")
                                        .HasColumnType("int")
                                        .HasColumnName("End");

                                    b2.Property<int>("Start")
                                        .HasColumnType("int")
                                        .HasColumnName("Start");

                                    b2.HasKey("StandingLabelLeagueId", "StandingLabelId");

                                    b2.ToTable("LeagueStandingLabels", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("StandingLabelLeagueId", "StandingLabelId");
                                });

                            b1.Navigation("Ranks")
                                .IsRequired();
                        });

                    b.OwnsOne("MyClub.Shared.Domain.Standings.Rules.StandingRuleSet", "StandingRules", b1 =>
                        {
                            b1.Property<Guid>("LeagueId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Columns")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Columns");

                            b1.Property<string>("Comparer")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Comparer");

                            b1.Property<string>("PointsByOutcome")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PointsByOutcome");

                            b1.HasKey("LeagueId");

                            b1.ToTable("LeagueStandingRuleSets", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LeagueId");
                        });

                    b.Navigation("Labels");

                    b.Navigation("StandingRules")
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.StageAggregate.ChampionshipStage", b =>
                {
                    b.OwnsMany("MyClub.Scorer.Domain.CompetitionAggregate.Configurations.StandingLabel", "Labels", b1 =>
                        {
                            b1.Property<Guid>("ChampionshipStageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Color")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Order")
                                .HasColumnType("int");

                            b1.Property<string>("ShortName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ChampionshipStageId", "Id");

                            b1.ToTable("ChampionshipStageStandingLabels", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChampionshipStageId");

                            b1.OwnsOne("Interval", "Ranks", b2 =>
                                {
                                    b2.Property<Guid>("StandingLabelChampionshipStageId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("StandingLabelId")
                                        .HasColumnType("int");

                                    b2.Property<int>("End")
                                        .HasColumnType("int")
                                        .HasColumnName("End");

                                    b2.Property<int>("Start")
                                        .HasColumnType("int")
                                        .HasColumnName("Start");

                                    b2.HasKey("StandingLabelChampionshipStageId", "StandingLabelId");

                                    b2.ToTable("ChampionshipStageStandingLabels", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("StandingLabelChampionshipStageId", "StandingLabelId");
                                });

                            b1.Navigation("Ranks")
                                .IsRequired();
                        });

                    b.OwnsOne("MyClub.Shared.Domain.Standings.Rules.StandingRuleSet", "StandingRules", b1 =>
                        {
                            b1.Property<Guid>("ChampionshipStageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Columns")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Columns");

                            b1.Property<string>("Comparer")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Comparer");

                            b1.Property<string>("PointsByOutcome")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PointsByOutcome");

                            b1.HasKey("ChampionshipStageId");

                            b1.ToTable("ChampionshipStageStandingRuleSets", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChampionshipStageId");
                        });

                    b.Navigation("Labels");

                    b.Navigation("StandingRules")
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.StageAggregate.GroupStage", b =>
                {
                    b.OwnsMany("MyClub.Scorer.Domain.CompetitionAggregate.Configurations.StandingLabel", "Labels", b1 =>
                        {
                            b1.Property<Guid>("GroupStageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Color")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Order")
                                .HasColumnType("int");

                            b1.Property<string>("ShortName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("GroupStageId", "Id");

                            b1.ToTable("GroupStageStandingLabels", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GroupStageId");

                            b1.OwnsOne("MyNet.Utilities.Sequences.Interval<int>", "Ranks", b2 =>
                                {
                                    b2.Property<Guid>("StandingLabelGroupStageId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("StandingLabelId")
                                        .HasColumnType("int");

                                    b2.Property<int>("End")
                                        .HasColumnType("int")
                                        .HasColumnName("End");

                                    b2.Property<int>("Start")
                                        .HasColumnType("int")
                                        .HasColumnName("Start");

                                    b2.HasKey("StandingLabelGroupStageId", "StandingLabelId");

                                    b2.ToTable("GroupStageStandingLabels", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("StandingLabelGroupStageId", "StandingLabelId");
                                });

                            b1.Navigation("Ranks")
                                .IsRequired();
                        });

                    b.OwnsOne("MyClub.Shared.Domain.Standings.Rules.StandingRuleSet", "StandingRules", b1 =>
                        {
                            b1.Property<Guid>("GroupStageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Columns")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Columns");

                            b1.Property<string>("Comparer")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Comparer");

                            b1.Property<string>("PointsByOutcome")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PointsByOutcome");

                            b1.HasKey("GroupStageId");

                            b1.ToTable("GroupStageStandingRuleSets", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GroupStageId");
                        });

                    b.Navigation("Labels");

                    b.Navigation("StandingRules")
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.CompetitionAggregate.Competition", b =>
                {
                    b.Navigation("Stadiums");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.CompetitionAggregate.Teams.Team", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.RoundAggregate.Round", b =>
                {
                    b.Navigation("Fixtures");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("MyClub.Scorer.Domain.StageAggregate.GroupStage", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
