/**
 * Play’Up Host HTTP client — domain modules under ./api/.
 * Prefer importing from this barrel (`../api`) so callers stay stable.
 * One fetch path only (see ./api/http.ts).
 */

export { ApiError } from './api/http';
export {
  fetchCompetitions,
  createCompetition,
  fetchCompetitionOverview,
  fetchCompetitionDetail,
  fetchStructureView,
  fetchConsultation,
  fetchNeedsAttention,
  replaceCompetitionRegulation,
  configureStructure,
  addCompetitionStage,
  removeCompetitionStage,
  prepareCompetition,
  startCompetition,
  completeCompetition,
  archiveCompetition,
} from './api/competitions';
export {
  addCompetitionEntry,
  updateEntryPresentation,
  renameCompetitionEntry,
  withdrawCompetitionEntry,
  addDeclaredMember,
  removeDeclaredMember,
  removeDeclaredMembers,
  renameDeclaredMember,
  deleteCompetitionEntry,
  deleteCompetitionEntries,
  withdrawCompetitionEntries,
} from './api/entries';
export { uploadMedia } from './api/media';
export {
  renameStage,
  rebuildStageStructure,
  replaceStageQualificationRules,
  replaceStageProgressionRules,
  replaceStagePlacementAwardRules,
  replaceStageMatchRules,
  replaceStageStandingRules,
  bindStageRegulation,
  replaceStageDrawRules,
  replaceStageAffectationAuthoring,
  assignEntryToSlot,
  clearSlotAssignment,
  replaceStageDefaultTieFormat,
  replaceRoundTieFormat,
  fetchStageOverview,
  fetchStageSchematic,
  applyProgressionOutcome,
  prepareStage,
  startStage,
  materializeMatches,
  generateNextSwissRound,
  materializeCupFromOccupiedSlots,
  applyQualification,
} from './api/stages';
export {
  fetchMatchHub,
  fetchMatchesByStage,
  fetchMatchDetail,
  startMatch,
  finishMatch,
  setRunningScore,
  addDeclaredParticipation,
  removeDeclaredParticipation,
  changeDeclaredParticipationCompositionStatus,
  setDeclaredParticipationJerseyNumber,
  recordGoal,
  correctRecordedGoal,
  removeRecordedGoal,
  recordSubstitution,
  correctRecordedSubstitution,
  removeRecordedSubstitution,
  recordDisciplinaryEvent,
  correctRecordedDisciplinaryEvent,
  removeRecordedDisciplinaryEvent,
} from './api/matches';
export {
  publishDraw,
  publishAndApplyDraw,
  cancelDraw,
  releaseDrawAlignedPlacements,
  createDraw,
  configureDrawInputs,
  generateDraw,
  createAndGenerateDraw,
  DrawGenerateFailedError,
  isDrawGenerateFailedError,
  applyDraw,
} from './api/draws';
