//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClub.CrossCutting.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyClubEnumsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyClubEnumsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyClub.CrossCutting.Localization.MyClubEnumsResources", typeof(MyClubEnumsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        public static string AttendanceAbsent {
            get {
                return ResourceManager.GetString("AttendanceAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excusé.
        /// </summary>
        public static string AttendanceApology {
            get {
                return ResourceManager.GetString("AttendanceApology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En vacances.
        /// </summary>
        public static string AttendanceInHolidays {
            get {
                return ResourceManager.GetString("AttendanceInHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blessé.
        /// </summary>
        public static string AttendanceInjured {
            get {
                return ResourceManager.GetString("AttendanceInjured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Sélection.
        /// </summary>
        public static string AttendanceInSelection {
            get {
                return ResourceManager.GetString("AttendanceInSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Présent.
        /// </summary>
        public static string AttendancePresent {
            get {
                return ResourceManager.GetString("AttendancePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnu.
        /// </summary>
        public static string AttendanceUnknown {
            get {
                return ResourceManager.GetString("AttendanceUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sénior.
        /// </summary>
        public static string CategoryAdult {
            get {
                return ResourceManager.GetString("CategoryAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string CategoryAdultAbbr {
            get {
                return ResourceManager.GetString("CategoryAdultAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vétéran.
        /// </summary>
        public static string CategorySeniors {
            get {
                return ResourceManager.GetString("CategorySeniors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string CategorySeniorsAbbr {
            get {
                return ResourceManager.GetString("CategorySeniorsAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U10.
        /// </summary>
        public static string CategoryU10 {
            get {
                return ResourceManager.GetString("CategoryU10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U10.
        /// </summary>
        public static string CategoryU10Abbr {
            get {
                return ResourceManager.GetString("CategoryU10Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U11.
        /// </summary>
        public static string CategoryU11 {
            get {
                return ResourceManager.GetString("CategoryU11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U11.
        /// </summary>
        public static string CategoryU11Abbr {
            get {
                return ResourceManager.GetString("CategoryU11Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U12.
        /// </summary>
        public static string CategoryU12 {
            get {
                return ResourceManager.GetString("CategoryU12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U12.
        /// </summary>
        public static string CategoryU12Abbr {
            get {
                return ResourceManager.GetString("CategoryU12Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U13.
        /// </summary>
        public static string CategoryU13 {
            get {
                return ResourceManager.GetString("CategoryU13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U13.
        /// </summary>
        public static string CategoryU13Abbr {
            get {
                return ResourceManager.GetString("CategoryU13Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U14.
        /// </summary>
        public static string CategoryU14 {
            get {
                return ResourceManager.GetString("CategoryU14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U14.
        /// </summary>
        public static string CategoryU14Abbr {
            get {
                return ResourceManager.GetString("CategoryU14Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U15.
        /// </summary>
        public static string CategoryU15 {
            get {
                return ResourceManager.GetString("CategoryU15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U15.
        /// </summary>
        public static string CategoryU15Abbr {
            get {
                return ResourceManager.GetString("CategoryU15Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U16.
        /// </summary>
        public static string CategoryU16 {
            get {
                return ResourceManager.GetString("CategoryU16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U16.
        /// </summary>
        public static string CategoryU16Abbr {
            get {
                return ResourceManager.GetString("CategoryU16Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U17.
        /// </summary>
        public static string CategoryU17 {
            get {
                return ResourceManager.GetString("CategoryU17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U17.
        /// </summary>
        public static string CategoryU17Abbr {
            get {
                return ResourceManager.GetString("CategoryU17Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U18.
        /// </summary>
        public static string CategoryU18 {
            get {
                return ResourceManager.GetString("CategoryU18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U18.
        /// </summary>
        public static string CategoryU18Abbr {
            get {
                return ResourceManager.GetString("CategoryU18Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U19.
        /// </summary>
        public static string CategoryU19 {
            get {
                return ResourceManager.GetString("CategoryU19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U19.
        /// </summary>
        public static string CategoryU19Abbr {
            get {
                return ResourceManager.GetString("CategoryU19Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U20.
        /// </summary>
        public static string CategoryU20 {
            get {
                return ResourceManager.GetString("CategoryU20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U20.
        /// </summary>
        public static string CategoryU20Abbr {
            get {
                return ResourceManager.GetString("CategoryU20Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U21.
        /// </summary>
        public static string CategoryU21 {
            get {
                return ResourceManager.GetString("CategoryU21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U21.
        /// </summary>
        public static string CategoryU21Abbr {
            get {
                return ResourceManager.GetString("CategoryU21Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U22.
        /// </summary>
        public static string CategoryU22 {
            get {
                return ResourceManager.GetString("CategoryU22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U22.
        /// </summary>
        public static string CategoryU22Abbr {
            get {
                return ResourceManager.GetString("CategoryU22Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U23.
        /// </summary>
        public static string CategoryU23 {
            get {
                return ResourceManager.GetString("CategoryU23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U23.
        /// </summary>
        public static string CategoryU23Abbr {
            get {
                return ResourceManager.GetString("CategoryU23Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U6.
        /// </summary>
        public static string CategoryU6 {
            get {
                return ResourceManager.GetString("CategoryU6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U6.
        /// </summary>
        public static string CategoryU6Abbr {
            get {
                return ResourceManager.GetString("CategoryU6Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U7.
        /// </summary>
        public static string CategoryU7 {
            get {
                return ResourceManager.GetString("CategoryU7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U7.
        /// </summary>
        public static string CategoryU7Abbr {
            get {
                return ResourceManager.GetString("CategoryU7Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U8.
        /// </summary>
        public static string CategoryU8 {
            get {
                return ResourceManager.GetString("CategoryU8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U8.
        /// </summary>
        public static string CategoryU8Abbr {
            get {
                return ResourceManager.GetString("CategoryU8Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U9.
        /// </summary>
        public static string CategoryU9 {
            get {
                return ResourceManager.GetString("CategoryU9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U9.
        /// </summary>
        public static string CategoryU9Abbr {
            get {
                return ResourceManager.GetString("CategoryU9Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupe.
        /// </summary>
        public static string CompetitionTypeCup {
            get {
                return ResourceManager.GetString("CompetitionTypeCup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amical.
        /// </summary>
        public static string CompetitionTypeFriendly {
            get {
                return ResourceManager.GetString("CompetitionTypeFriendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Championnat.
        /// </summary>
        public static string CompetitionTypeLeague {
            get {
                return ResourceManager.GetString("CompetitionTypeLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercice.
        /// </summary>
        public static string ExerciceTypeExercice {
            get {
                return ResourceManager.GetString("ExerciceTypeExercice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeu.
        /// </summary>
        public static string ExerciceTypeGame {
            get {
                return ResourceManager.GetString("ExerciceTypeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre.
        /// </summary>
        public static string ExerciceTypeOther {
            get {
                return ResourceManager.GetString("ExerciceTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situation.
        /// </summary>
        public static string ExerciceTypeSituation {
            get {
                return ResourceManager.GetString("ExerciceTypeSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echauffement.
        /// </summary>
        public static string ExerciceTypeWarmUp {
            get {
                return ResourceManager.GetString("ExerciceTypeWarmUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthétique.
        /// </summary>
        public static string GroundArtificialGrass {
            get {
                return ResourceManager.GetString("GroundArtificialGrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herbe.
        /// </summary>
        public static string GroundGrass {
            get {
                return ResourceManager.GetString("GroundGrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salle.
        /// </summary>
        public static string GroundIndoor {
            get {
                return ResourceManager.GetString("GroundIndoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sable.
        /// </summary>
        public static string GroundSand {
            get {
                return ResourceManager.GetString("GroundSand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string ImportModeAdd {
            get {
                return ResourceManager.GetString("ImportModeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string ImportModeUpdate {
            get {
                return ResourceManager.GetString("ImportModeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pubalgie.
        /// </summary>
        public static string InjuryAdductors {
            get {
                return ResourceManager.GetString("InjuryAdductors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Douleurs au dos.
        /// </summary>
        public static string InjuryBack {
            get {
                return ResourceManager.GetString("InjuryBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture.
        /// </summary>
        public static string InjuryCategoryFracture {
            get {
                return ResourceManager.GetString("InjuryCategoryFracture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligamentaire.
        /// </summary>
        public static string InjuryCategoryLigament {
            get {
                return ResourceManager.GetString("InjuryCategoryLigament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musculaire.
        /// </summary>
        public static string InjuryCategoryMuscular {
            get {
                return ResourceManager.GetString("InjuryCategoryMuscular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre.
        /// </summary>
        public static string InjuryCategoryOther {
            get {
                return ResourceManager.GetString("InjuryCategoryOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maladie.
        /// </summary>
        public static string InjuryCategorySickness {
            get {
                return ResourceManager.GetString("InjuryCategorySickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traumatisme.
        /// </summary>
        public static string InjuryCategoryTrauma {
            get {
                return ResourceManager.GetString("InjuryCategoryTrauma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contusion à la tête.
        /// </summary>
        public static string InjuryHead {
            get {
                return ResourceManager.GetString("InjuryHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entorse de la cheville gauche.
        /// </summary>
        public static string InjuryLeftAnkle {
            get {
                return ResourceManager.GetString("InjuryLeftAnkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture du bras gauche.
        /// </summary>
        public static string InjuryLeftArm {
            get {
                return ResourceManager.GetString("InjuryLeftArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elongation du mollet gauche.
        /// </summary>
        public static string InjuryLeftCalf {
            get {
                return ResourceManager.GetString("InjuryLeftCalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture du coude gauche.
        /// </summary>
        public static string InjuryLeftElbow {
            get {
                return ResourceManager.GetString("InjuryLeftElbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture du pied gauche.
        /// </summary>
        public static string InjuryLeftFoot {
            get {
                return ResourceManager.GetString("InjuryLeftFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contusion à la main gauche.
        /// </summary>
        public static string InjuryLeftHand {
            get {
                return ResourceManager.GetString("InjuryLeftHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entorse du genou gauche.
        /// </summary>
        public static string InjuryLeftKnee {
            get {
                return ResourceManager.GetString("InjuryLeftKnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture du tibia gauche.
        /// </summary>
        public static string InjuryLeftShin {
            get {
                return ResourceManager.GetString("InjuryLeftShin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxation de l&apos;épaule gauche.
        /// </summary>
        public static string InjuryLeftShoulder {
            get {
                return ResourceManager.GetString("InjuryLeftShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déchirure à la cuisse gauche.
        /// </summary>
        public static string InjuryLeftThigh {
            get {
                return ResourceManager.GetString("InjuryLeftThigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entorse du poignet gauche.
        /// </summary>
        public static string InjuryLeftWrist {
            get {
                return ResourceManager.GetString("InjuryLeftWrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Douleurs aux cervicales.
        /// </summary>
        public static string InjuryNeck {
            get {
                return ResourceManager.GetString("InjuryNeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blessure(s).
        /// </summary>
        public static string InjuryOptionalPlural {
            get {
                return ResourceManager.GetString("InjuryOptionalPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entorse de la cheville droite.
        /// </summary>
        public static string InjuryRightAnkle {
            get {
                return ResourceManager.GetString("InjuryRightAnkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture du bras droit.
        /// </summary>
        public static string InjuryRightArm {
            get {
                return ResourceManager.GetString("InjuryRightArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elongation du mollet droit.
        /// </summary>
        public static string InjuryRightCalf {
            get {
                return ResourceManager.GetString("InjuryRightCalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture du coude droit.
        /// </summary>
        public static string InjuryRightElbow {
            get {
                return ResourceManager.GetString("InjuryRightElbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture du pied droit.
        /// </summary>
        public static string InjuryRightFoot {
            get {
                return ResourceManager.GetString("InjuryRightFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contusion à la main droite.
        /// </summary>
        public static string InjuryRightHand {
            get {
                return ResourceManager.GetString("InjuryRightHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entorse du genou droit.
        /// </summary>
        public static string InjuryRightKnee {
            get {
                return ResourceManager.GetString("InjuryRightKnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture du tibia droit.
        /// </summary>
        public static string InjuryRightShin {
            get {
                return ResourceManager.GetString("InjuryRightShin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxation de l&apos;épaule droite.
        /// </summary>
        public static string InjuryRightShoulder {
            get {
                return ResourceManager.GetString("InjuryRightShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déchirure à la cuisse droite.
        /// </summary>
        public static string InjuryRightThigh {
            get {
                return ResourceManager.GetString("InjuryRightThigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entorse du poignet droit.
        /// </summary>
        public static string InjuryRightWrist {
            get {
                return ResourceManager.GetString("InjuryRightWrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mineure.
        /// </summary>
        public static string InjurySeverityMinor {
            get {
                return ResourceManager.GetString("InjurySeverityMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modérée.
        /// </summary>
        public static string InjurySeverityModerate {
            get {
                return ResourceManager.GetString("InjurySeverityModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sérieuse.
        /// </summary>
        public static string InjurySeveritySerious {
            get {
                return ResourceManager.GetString("InjurySeveritySerious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sévère.
        /// </summary>
        public static string InjurySeveritySevere {
            get {
                return ResourceManager.GetString("InjurySeveritySevere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mal au ventre.
        /// </summary>
        public static string InjuryStomach {
            get {
                return ResourceManager.GetString("InjuryStomach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Côtes fracturées.
        /// </summary>
        public static string InjuryTorso {
            get {
                return ResourceManager.GetString("InjuryTorso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adducteurs.
        /// </summary>
        public static string InjuryTypeAdductors {
            get {
                return ResourceManager.GetString("InjuryTypeAdductors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dos.
        /// </summary>
        public static string InjuryTypeBack {
            get {
                return ResourceManager.GetString("InjuryTypeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tête.
        /// </summary>
        public static string InjuryTypeHead {
            get {
                return ResourceManager.GetString("InjuryTypeHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheville gauche.
        /// </summary>
        public static string InjuryTypeLeftAnkle {
            get {
                return ResourceManager.GetString("InjuryTypeLeftAnkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bras gauche.
        /// </summary>
        public static string InjuryTypeLeftArm {
            get {
                return ResourceManager.GetString("InjuryTypeLeftArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mollet gauche.
        /// </summary>
        public static string InjuryTypeLeftCalf {
            get {
                return ResourceManager.GetString("InjuryTypeLeftCalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coude gauche.
        /// </summary>
        public static string InjuryTypeLeftElbow {
            get {
                return ResourceManager.GetString("InjuryTypeLeftElbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pied gauche.
        /// </summary>
        public static string InjuryTypeLeftFoot {
            get {
                return ResourceManager.GetString("InjuryTypeLeftFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main gauche.
        /// </summary>
        public static string InjuryTypeLeftHand {
            get {
                return ResourceManager.GetString("InjuryTypeLeftHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genou gauche.
        /// </summary>
        public static string InjuryTypeLeftKnee {
            get {
                return ResourceManager.GetString("InjuryTypeLeftKnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia gauche.
        /// </summary>
        public static string InjuryTypeLeftShin {
            get {
                return ResourceManager.GetString("InjuryTypeLeftShin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epaule gauche.
        /// </summary>
        public static string InjuryTypeLeftShoulder {
            get {
                return ResourceManager.GetString("InjuryTypeLeftShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuisse gauche.
        /// </summary>
        public static string InjuryTypeLeftThigh {
            get {
                return ResourceManager.GetString("InjuryTypeLeftThigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poignet gauche.
        /// </summary>
        public static string InjuryTypeLeftWrist {
            get {
                return ResourceManager.GetString("InjuryTypeLeftWrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cou.
        /// </summary>
        public static string InjuryTypeNeck {
            get {
                return ResourceManager.GetString("InjuryTypeNeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre.
        /// </summary>
        public static string InjuryTypeOther {
            get {
                return ResourceManager.GetString("InjuryTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheville droite.
        /// </summary>
        public static string InjuryTypeRightAnkle {
            get {
                return ResourceManager.GetString("InjuryTypeRightAnkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bras droit.
        /// </summary>
        public static string InjuryTypeRightArm {
            get {
                return ResourceManager.GetString("InjuryTypeRightArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mollet Droit.
        /// </summary>
        public static string InjuryTypeRightCalf {
            get {
                return ResourceManager.GetString("InjuryTypeRightCalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coude droit.
        /// </summary>
        public static string InjuryTypeRightElbow {
            get {
                return ResourceManager.GetString("InjuryTypeRightElbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pied droit.
        /// </summary>
        public static string InjuryTypeRightFoot {
            get {
                return ResourceManager.GetString("InjuryTypeRightFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main droite.
        /// </summary>
        public static string InjuryTypeRightHand {
            get {
                return ResourceManager.GetString("InjuryTypeRightHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genou droit.
        /// </summary>
        public static string InjuryTypeRightKnee {
            get {
                return ResourceManager.GetString("InjuryTypeRightKnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia droit.
        /// </summary>
        public static string InjuryTypeRightShin {
            get {
                return ResourceManager.GetString("InjuryTypeRightShin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epaule droite.
        /// </summary>
        public static string InjuryTypeRightShoulder {
            get {
                return ResourceManager.GetString("InjuryTypeRightShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuisse droite.
        /// </summary>
        public static string InjuryTypeRightThigh {
            get {
                return ResourceManager.GetString("InjuryTypeRightThigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poignet droit.
        /// </summary>
        public static string InjuryTypeRightWrist {
            get {
                return ResourceManager.GetString("InjuryTypeRightWrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abdomen.
        /// </summary>
        public static string InjuryTypeStomach {
            get {
                return ResourceManager.GetString("InjuryTypeStomach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torse.
        /// </summary>
        public static string InjuryTypeTorso {
            get {
                return ResourceManager.GetString("InjuryTypeTorso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom complet.
        /// </summary>
        public static string InverseName {
            get {
                return ResourceManager.GetString("InverseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-4-3.
        /// </summary>
        public static string KnownTactic_343 {
            get {
                return ResourceManager.GetString("KnownTactic_343", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-2-2-2.
        /// </summary>
        public static string KnownTactic_4222 {
            get {
                return ResourceManager.GetString("KnownTactic_4222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-2-3-1.
        /// </summary>
        public static string KnownTactic_4231 {
            get {
                return ResourceManager.GetString("KnownTactic_4231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-2-4.
        /// </summary>
        public static string KnownTactic_424 {
            get {
                return ResourceManager.GetString("KnownTactic_424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-3-2-1.
        /// </summary>
        public static string KnownTactic_4321 {
            get {
                return ResourceManager.GetString("KnownTactic_4321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-3-3 Défensif.
        /// </summary>
        public static string KnownTactic_433Defensive {
            get {
                return ResourceManager.GetString("KnownTactic_433Defensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-3-3 Offensif.
        /// </summary>
        public static string KnownTactic_433Offensive {
            get {
                return ResourceManager.GetString("KnownTactic_433Offensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-4-2.
        /// </summary>
        public static string KnownTactic_442 {
            get {
                return ResourceManager.GetString("KnownTactic_442", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-4-2 Losange.
        /// </summary>
        public static string KnownTactic_442Diamond {
            get {
                return ResourceManager.GetString("KnownTactic_442Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-2-1-2.
        /// </summary>
        public static string KnownTactic_5212 {
            get {
                return ResourceManager.GetString("KnownTactic_5212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-2-2-1.
        /// </summary>
        public static string KnownTactic_5221 {
            get {
                return ResourceManager.GetString("KnownTactic_5221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-2-3.
        /// </summary>
        public static string KnownTactic_523 {
            get {
                return ResourceManager.GetString("KnownTactic_523", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-3-2.
        /// </summary>
        public static string KnownTactic_532 {
            get {
                return ResourceManager.GetString("KnownTactic_532", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaucher.
        /// </summary>
        public static string LateralityLeftHander {
            get {
                return ResourceManager.GetString("LateralityLeftHander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droitier.
        /// </summary>
        public static string LateralityRightHander {
            get {
                return ResourceManager.GetString("LateralityRightHander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnue.
        /// </summary>
        public static string LateralityUnknown {
            get {
                return ResourceManager.GetString("LateralityUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendue.
        /// </summary>
        public static string LicenseStateBack {
            get {
                return ResourceManager.GetString("LicenseStateBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donnée.
        /// </summary>
        public static string LicenseStateGiven {
            get {
                return ResourceManager.GetString("LicenseStateGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payée.
        /// </summary>
        public static string LicenseStatePaid {
            get {
                return ResourceManager.GetString("LicenseStatePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnu.
        /// </summary>
        public static string LicenseStateUnknown {
            get {
                return ResourceManager.GetString("LicenseStateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En cours.
        /// </summary>
        public static string MatchStateInProgress {
            get {
                return ResourceManager.GetString("MatchStateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A venir.
        /// </summary>
        public static string MatchStateNone {
            get {
                return ResourceManager.GetString("MatchStateNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joué.
        /// </summary>
        public static string MatchStatePlayed {
            get {
                return ResourceManager.GetString("MatchStatePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporté.
        /// </summary>
        public static string MatchStatePostponed {
            get {
                return ResourceManager.GetString("MatchStatePostponed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêté.
        /// </summary>
        public static string MatchStateSuspended {
            get {
                return ResourceManager.GetString("MatchStateSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu offensif axial.
        /// </summary>
        public static string PositionCenterAttackingMidfielder {
            get {
                return ResourceManager.GetString("PositionCenterAttackingMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOC.
        /// </summary>
        public static string PositionCenterAttackingMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionCenterAttackingMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Défenseur central.
        /// </summary>
        public static string PositionCenterBack {
            get {
                return ResourceManager.GetString("PositionCenterBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC.
        /// </summary>
        public static string PositionCenterBackAbbr {
            get {
                return ResourceManager.GetString("PositionCenterBackAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu offensif.
        /// </summary>
        public static string PositionCenterLeftAttackingMidfielder {
            get {
                return ResourceManager.GetString("PositionCenterLeftAttackingMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MO.
        /// </summary>
        public static string PositionCenterLeftAttackingMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionCenterLeftAttackingMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Défenseur central.
        /// </summary>
        public static string PositionCenterLeftBack {
            get {
                return ResourceManager.GetString("PositionCenterLeftBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC.
        /// </summary>
        public static string PositionCenterLeftBackAbbr {
            get {
                return ResourceManager.GetString("PositionCenterLeftBackAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu axial.
        /// </summary>
        public static string PositionCenterLeftMidfielder {
            get {
                return ResourceManager.GetString("PositionCenterLeftMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC.
        /// </summary>
        public static string PositionCenterLeftMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionCenterLeftMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu axial.
        /// </summary>
        public static string PositionCenterMidfielder {
            get {
                return ResourceManager.GetString("PositionCenterMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC.
        /// </summary>
        public static string PositionCenterMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionCenterMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu offensif.
        /// </summary>
        public static string PositionCenterRightAttackingMidfielder {
            get {
                return ResourceManager.GetString("PositionCenterRightAttackingMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MO.
        /// </summary>
        public static string PositionCenterRightAttackingMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionCenterRightAttackingMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Défenseur central.
        /// </summary>
        public static string PositionCenterRightBack {
            get {
                return ResourceManager.GetString("PositionCenterRightBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC.
        /// </summary>
        public static string PositionCenterRightBackAbbr {
            get {
                return ResourceManager.GetString("PositionCenterRightBackAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu axial.
        /// </summary>
        public static string PositionCenterRightMidfielder {
            get {
                return ResourceManager.GetString("PositionCenterRightMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC.
        /// </summary>
        public static string PositionCenterRightMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionCenterRightMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu défensif.
        /// </summary>
        public static string PositionDefensiveLeftMidfielder {
            get {
                return ResourceManager.GetString("PositionDefensiveLeftMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD.
        /// </summary>
        public static string PositionDefensiveLeftMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionDefensiveLeftMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu défensif.
        /// </summary>
        public static string PositionDefensiveMidfielder {
            get {
                return ResourceManager.GetString("PositionDefensiveMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDC.
        /// </summary>
        public static string PositionDefensiveMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionDefensiveMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu défensif.
        /// </summary>
        public static string PositionDefensiveRightMidfielder {
            get {
                return ResourceManager.GetString("PositionDefensiveRightMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD.
        /// </summary>
        public static string PositionDefensiveRightMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionDefensiveRightMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaquant.
        /// </summary>
        public static string PositionForward {
            get {
                return ResourceManager.GetString("PositionForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATT.
        /// </summary>
        public static string PositionForwardAbbr {
            get {
                return ResourceManager.GetString("PositionForwardAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gardien.
        /// </summary>
        public static string PositionGoalKeeper {
            get {
                return ResourceManager.GetString("PositionGoalKeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        public static string PositionGoalKeeperAbbr {
            get {
                return ResourceManager.GetString("PositionGoalKeeperAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu offensif gauche.
        /// </summary>
        public static string PositionLeftAttackingMidfielder {
            get {
                return ResourceManager.GetString("PositionLeftAttackingMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOG.
        /// </summary>
        public static string PositionLeftAttackingMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionLeftAttackingMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaquant.
        /// </summary>
        public static string PositionLeftForward {
            get {
                return ResourceManager.GetString("PositionLeftForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATT.
        /// </summary>
        public static string PositionLeftForwardAbbr {
            get {
                return ResourceManager.GetString("PositionLeftForwardAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrière gauche.
        /// </summary>
        public static string PositionLeftFullBack {
            get {
                return ResourceManager.GetString("PositionLeftFullBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DG.
        /// </summary>
        public static string PositionLeftFullBackAbbr {
            get {
                return ResourceManager.GetString("PositionLeftFullBackAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu gauche.
        /// </summary>
        public static string PositionLeftMidfielder {
            get {
                return ResourceManager.GetString("PositionLeftMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MG.
        /// </summary>
        public static string PositionLeftMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionLeftMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latéral gauche.
        /// </summary>
        public static string PositionLeftWingBack {
            get {
                return ResourceManager.GetString("PositionLeftWingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LG.
        /// </summary>
        public static string PositionLeftWingBackAbbr {
            get {
                return ResourceManager.GetString("PositionLeftWingBackAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ailier gauche.
        /// </summary>
        public static string PositionLeftWinger {
            get {
                return ResourceManager.GetString("PositionLeftWinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AG.
        /// </summary>
        public static string PositionLeftWingerAbbr {
            get {
                return ResourceManager.GetString("PositionLeftWingerAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peu convaincant.
        /// </summary>
        public static string PositionRatingAverage {
            get {
                return ResourceManager.GetString("PositionRatingAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string PositionRatingGood {
            get {
                return ResourceManager.GetString("PositionRatingGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inneficace.
        /// </summary>
        public static string PositionRatingInefficient {
            get {
                return ResourceManager.GetString("PositionRatingInefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturel.
        /// </summary>
        public static string PositionRatingNatural {
            get {
                return ResourceManager.GetString("PositionRatingNatural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mal à l&apos;aise.
        /// </summary>
        public static string PositionRatingPoor {
            get {
                return ResourceManager.GetString("PositionRatingPoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accompli.
        /// </summary>
        public static string PositionRatingVeryGood {
            get {
                return ResourceManager.GetString("PositionRatingVeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu offensif droit.
        /// </summary>
        public static string PositionRightAttackingMidfielder {
            get {
                return ResourceManager.GetString("PositionRightAttackingMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOD.
        /// </summary>
        public static string PositionRightAttackingMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionRightAttackingMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaquant.
        /// </summary>
        public static string PositionRightForward {
            get {
                return ResourceManager.GetString("PositionRightForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATT.
        /// </summary>
        public static string PositionRightForwardAbbr {
            get {
                return ResourceManager.GetString("PositionRightForwardAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrière droit.
        /// </summary>
        public static string PositionRightFullBack {
            get {
                return ResourceManager.GetString("PositionRightFullBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD.
        /// </summary>
        public static string PositionRightFullBackAbbr {
            get {
                return ResourceManager.GetString("PositionRightFullBackAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu droit.
        /// </summary>
        public static string PositionRightMidfielder {
            get {
                return ResourceManager.GetString("PositionRightMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD.
        /// </summary>
        public static string PositionRightMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionRightMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latéral droit.
        /// </summary>
        public static string PositionRightWingBack {
            get {
                return ResourceManager.GetString("PositionRightWingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LD.
        /// </summary>
        public static string PositionRightWingBackAbbr {
            get {
                return ResourceManager.GetString("PositionRightWingBackAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ailier droit.
        /// </summary>
        public static string PositionRightWinger {
            get {
                return ResourceManager.GetString("PositionRightWinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD.
        /// </summary>
        public static string PositionRightWingerAbbr {
            get {
                return ResourceManager.GetString("PositionRightWingerAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        public static string PositionSideCenter {
            get {
                return ResourceManager.GetString("PositionSideCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauche.
        /// </summary>
        public static string PositionSideLeft {
            get {
                return ResourceManager.GetString("PositionSideLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droit.
        /// </summary>
        public static string PositionSideRight {
            get {
                return ResourceManager.GetString("PositionSideRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libéro.
        /// </summary>
        public static string PositionSweeper {
            get {
                return ResourceManager.GetString("PositionSweeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string PositionSweeperAbbr {
            get {
                return ResourceManager.GetString("PositionSweeperAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millieu Offensif.
        /// </summary>
        public static string PositionTypeAttackingMidfielder {
            get {
                return ResourceManager.GetString("PositionTypeAttackingMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Défenseur.
        /// </summary>
        public static string PositionTypeCenterBack {
            get {
                return ResourceManager.GetString("PositionTypeCenterBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Défenseur.
        /// </summary>
        public static string PositionTypeDefender {
            get {
                return ResourceManager.GetString("PositionTypeDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu défensif.
        /// </summary>
        public static string PositionTypeDefensiveMidfielder {
            get {
                return ResourceManager.GetString("PositionTypeDefensiveMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaquant.
        /// </summary>
        public static string PositionTypeForward {
            get {
                return ResourceManager.GetString("PositionTypeForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrière.
        /// </summary>
        public static string PositionTypeFullBack {
            get {
                return ResourceManager.GetString("PositionTypeFullBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gardien.
        /// </summary>
        public static string PositionTypeGoalKeeper {
            get {
                return ResourceManager.GetString("PositionTypeGoalKeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu.
        /// </summary>
        public static string PositionTypeMidfielder {
            get {
                return ResourceManager.GetString("PositionTypeMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buteur.
        /// </summary>
        public static string PositionTypeStriker {
            get {
                return ResourceManager.GetString("PositionTypeStriker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libéro.
        /// </summary>
        public static string PositionTypeSweeper {
            get {
                return ResourceManager.GetString("PositionTypeSweeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latéral.
        /// </summary>
        public static string PositionTypeWingBack {
            get {
                return ResourceManager.GetString("PositionTypeWingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ailier.
        /// </summary>
        public static string PositionTypeWinger {
            get {
                return ResourceManager.GetString("PositionTypeWinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Différence de buts.
        /// </summary>
        public static string RankingSortingColumnGoalDifference {
            get {
                return ResourceManager.GetString("RankingSortingColumnGoalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buts marqués.
        /// </summary>
        public static string RankingSortingColumnGoalsAgainst {
            get {
                return ResourceManager.GetString("RankingSortingColumnGoalsAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buts encaissés.
        /// </summary>
        public static string RankingSortingColumnGoalsFor {
            get {
                return ResourceManager.GetString("RankingSortingColumnGoalsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string RankingSortingColumnPoints {
            get {
                return ResourceManager.GetString("RankingSortingColumnPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal average particulier.
        /// </summary>
        public static string RankingSortingColumnResultsBetweenTeams {
            get {
                return ResourceManager.GetString("RankingSortingColumnResultsBetweenTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de victoires.
        /// </summary>
        public static string RankingSortingColumnWins {
            get {
                return ResourceManager.GetString("RankingSortingColumnWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string RecentFilesSortingPropertyLastAccessDate {
            get {
                return ResourceManager.GetString("RecentFilesSortingPropertyLastAccessDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string RecentFilesSortingPropertyName {
            get {
                return ResourceManager.GetString("RecentFilesSortingPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brouillon.
        /// </summary>
        public static string SendingStateDraft {
            get {
                return ResourceManager.GetString("SendingStateDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echoué.
        /// </summary>
        public static string SendingStateFailed {
            get {
                return ResourceManager.GetString("SendingStateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Cours.
        /// </summary>
        public static string SendingStateInProgress {
            get {
                return ResourceManager.GetString("SendingStateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succès.
        /// </summary>
        public static string SendingStateSuccess {
            get {
                return ResourceManager.GetString("SendingStateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnu.
        /// </summary>
        public static string SendingStateUnknown {
            get {
                return ResourceManager.GetString("SendingStateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupe.
        /// </summary>
        public static string TournamentTypeCup {
            get {
                return ResourceManager.GetString("TournamentTypeCup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligue.
        /// </summary>
        public static string TournamentTypeLeague {
            get {
                return ResourceManager.GetString("TournamentTypeLeague", resourceCulture);
            }
        }
    }
}
