<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="MediatR" Version="13.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0-preview.6.25358.103" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0-preview.6.25358.103" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MyClub.Shared.Kernel\MyClub.Shared.Kernel.csproj" />
    </ItemGroup>

</Project>
