//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClub.Plugins.Base.File.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyClub.Plugins.Base.File.Resources.FileResources", typeof(FileResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonne :.
        /// </summary>
        internal static string ImportColumn {
            get {
                return ResourceManager.GetString("ImportColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Des colonnes sont manquantes..
        /// </summary>
        internal static string ImportColumnsAreMissing {
            get {
                return ResourceManager.GetString("ImportColumnsAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elles seront remplacées par des valeurs par défaut..
        /// </summary>
        internal static string ImportDefaultValues {
            get {
                return ResourceManager.GetString("ImportDefaultValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécharger le fichier d&apos;exemple.
        /// </summary>
        internal static string ImportDownloadSampleFile {
            get {
                return ResourceManager.GetString("ImportDownloadSampleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue à la ligne #.
        /// </summary>
        internal static string ImportErrorInRowFormat {
            get {
                return ResourceManager.GetString("ImportErrorInRowFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner un fichier contenant des éléments à importer.
        /// </summary>
        internal static string ImportFromFileDescription {
            get {
                return ResourceManager.GetString("ImportFromFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Des erreurs sont survenues lors de l&apos;import de votre fichier.
        /// </summary>
        internal static string ImportHasErrors {
            get {
                return ResourceManager.GetString("ImportHasErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorer les erreurs et importer les lignes valides.
        /// </summary>
        internal static string ImportIgnoreErrors {
            get {
                return ResourceManager.GetString("ImportIgnoreErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligne :.
        /// </summary>
        internal static string ImportRow {
            get {
                return ResourceManager.GetString("ImportRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ligne sera ignorée.
        /// </summary>
        internal static string ImportRowWillBeIgnored {
            get {
                return ResourceManager.GetString("ImportRowWillBeIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (n&apos;oubliez pas de sauvegarder votre fichier avant de le recharger).
        /// </summary>
        internal static string ImportSaveBeforeReload {
            get {
                return ResourceManager.GetString("ImportSaveBeforeReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier votre fichier.
        /// </summary>
        internal static string ImportSetFile {
            get {
                return ResourceManager.GetString("ImportSetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La valeur sera ignorée.
        /// </summary>
        internal static string ImportValueWillBeIgnored {
            get {
                return ResourceManager.GetString("ImportValueWillBeIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharger.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner un fichier.
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
    }
}
