<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\..\Shared\MyClub.Shared.Domain\MyClub.Shared.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>MyClub.Scorer.Infrastructure.Persistence</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
</Project>