// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyClub.PlayUp.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyClub.PlayUp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlayUpDbContext))]
    [Migration("20260814123211_DeferStageSortOrderUniques")]
    partial class DeferStageSortOrderUniques
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyClub.PlayUp.Domain.Competitions.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CompletionMode")
                        .HasColumnType("integer")
                        .HasColumnName("completion_mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Regulation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("regulation");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("competitions", (string)null);
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AwayEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_entry_id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<Guid>("HomeEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_entry_id");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("StageId");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Stages.Fixture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("SlotAKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slot_a_key");

                    b.Property<string>("SlotBKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slot_b_key");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid?>("matchday_id")
                        .HasColumnType("uuid")
                        .HasColumnName("matchday_id");

                    b.Property<Guid?>("round_id")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.HasKey("Id");

                    b.HasIndex("matchday_id");

                    b.HasIndex("round_id");

                    b.ToTable("fixtures", null, t =>
                        {
                            t.HasCheckConstraint("CK_fixtures_round_xor_matchday", "(\"round_id\" IS NOT NULL AND \"matchday_id\" IS NULL) OR (\"round_id\" IS NULL AND \"matchday_id\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Stages.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("stage_id")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.HasKey("Id");

                    b.HasIndex("stage_id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Stages.Matchday", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("stage_id")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.HasKey("Id");

                    b.HasIndex("stage_id");

                    b.ToTable("matchdays", (string)null);
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Stages.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TieFormat")
                        .HasColumnType("jsonb")
                        .HasColumnName("tie_format");

                    b.Property<Guid>("stage_id")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.HasKey("Id");

                    b.HasIndex("stage_id");

                    b.ToTable("rounds", (string)null);
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Stages.Slot", b =>
                {
                    b.Property<Guid>("stage_id")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<string>("SlotKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slot_key");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.HasKey("stage_id", "SlotKey");

                    b.ToTable("slots", (string)null);
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Stages.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Regulation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stage_regulation");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("stages", (string)null);
                });

            modelBuilder.Entity("MyClub.PlayUp.Infrastructure.Persistence.CompetitionStageRef", b =>
                {
                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("CompetitionId", "StageId");

                    b.HasIndex("StageId");

                    b.ToTable("competition_stage_refs", (string)null);
                });

            modelBuilder.Entity("MyClub.PlayUp.Infrastructure.Persistence.FixtureAttachmentRef", b =>
                {
                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uuid")
                        .HasColumnName("fixture_id");

                    b.Property<int>("LegIndex")
                        .HasColumnType("integer")
                        .HasColumnName("leg_index");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.HasKey("FixtureId", "LegIndex");

                    b.HasIndex("MatchId");

                    b.ToTable("fixture_attachments", (string)null);
                });

            modelBuilder.Entity("MyClub.PlayUp.Infrastructure.Persistence.GroupEntryRef", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("GroupId", "EntryId");

                    b.ToTable("group_entries", (string)null);
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Competitions.Competition", b =>
                {
                    b.OwnsMany("MyClub.PlayUp.Domain.Competitions.CompetitionEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("display_name");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("integer")
                                .HasColumnName("sort_order");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uuid")
                                .HasColumnName("team_id");

                            b1.Property<Guid>("competition_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("competition_id", "SortOrder")
                                .IsUnique();

                            b1.ToTable("competition_entries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("competition_id");
                        });

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Matches.Match", b =>
                {
                    b.HasOne("MyClub.PlayUp.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyClub.PlayUp.Domain.Stages.Stage", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Stages.Fixture", b =>
                {
                    b.HasOne("MyClub.PlayUp.Domain.Stages.Matchday", null)
                        .WithMany("Fixtures")
                        .HasForeignKey("matchday_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyClub.PlayUp.Domain.Stages.Round", null)
                        .WithMany("Fixtures")
                        .HasForeignKey("round_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Stages.Group", b =>
                {
                    b.HasOne("MyClub.PlayUp.Domain.Stages.Stage", null)
                        .WithMany("Groups")
                        .HasForeignKey("stage_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Stages.Matchday", b =>
                {
                    b.HasOne("MyClub.PlayUp.Domain.Stages.Stage", null)
                        .WithMany("Matchdays")
                        .HasForeignKey("stage_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Stages.Round", b =>
                {
                    b.HasOne("MyClub.PlayUp.Domain.Stages.Stage", null)
                        .WithMany("Rounds")
                        .HasForeignKey("stage_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Stages.Slot", b =>
                {
                    b.HasOne("MyClub.PlayUp.Domain.Stages.Stage", null)
                        .WithMany("Slots")
                        .HasForeignKey("stage_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Stages.Stage", b =>
                {
                    b.HasOne("MyClub.PlayUp.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("MyClub.PlayUp.Domain.Stages.DirectAssignment", "DirectAssignments", b1 =>
                        {
                            b1.Property<Guid>("stage_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("SlotKey")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("slot_key");

                            b1.Property<Guid>("EntryId")
                                .HasColumnType("uuid")
                                .HasColumnName("entry_id");

                            b1.HasKey("stage_id", "SlotKey");

                            b1.ToTable("stage_direct_assignments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("stage_id");
                        });

                    b.Navigation("DirectAssignments");
                });

            modelBuilder.Entity("MyClub.PlayUp.Infrastructure.Persistence.CompetitionStageRef", b =>
                {
                    b.HasOne("MyClub.PlayUp.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyClub.PlayUp.Domain.Stages.Stage", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.PlayUp.Infrastructure.Persistence.FixtureAttachmentRef", b =>
                {
                    b.HasOne("MyClub.PlayUp.Domain.Stages.Fixture", null)
                        .WithMany()
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyClub.PlayUp.Domain.Matches.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.PlayUp.Infrastructure.Persistence.GroupEntryRef", b =>
                {
                    b.HasOne("MyClub.PlayUp.Domain.Stages.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Stages.Matchday", b =>
                {
                    b.Navigation("Fixtures");
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Stages.Round", b =>
                {
                    b.Navigation("Fixtures");
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Stages.Stage", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Matchdays");

                    b.Navigation("Rounds");

                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
