// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyClub.PlayUp.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyClub.PlayUp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlayUpDbContext))]
    [Migration("20260814113905_AddMatch")]
    partial class AddMatch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyClub.PlayUp.Domain.Competitions.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CompletionMode")
                        .HasColumnType("integer")
                        .HasColumnName("completion_mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Regulation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("regulation");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("competitions", (string)null);
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AwayEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_entry_id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<Guid>("HomeEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_entry_id");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("MyClub.PlayUp.Infrastructure.Persistence.CompetitionStageRef", b =>
                {
                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("CompetitionId", "StageId");

                    b.ToTable("competition_stage_refs", (string)null);
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Competitions.Competition", b =>
                {
                    b.OwnsMany("MyClub.PlayUp.Domain.Competitions.CompetitionEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("display_name");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("integer")
                                .HasColumnName("sort_order");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uuid")
                                .HasColumnName("team_id");

                            b1.Property<Guid>("competition_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("competition_id", "SortOrder")
                                .IsUnique();

                            b1.ToTable("competition_entries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("competition_id");
                        });

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("MyClub.PlayUp.Domain.Matches.Match", b =>
                {
                    b.HasOne("MyClub.PlayUp.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyClub.PlayUp.Infrastructure.Persistence.CompetitionStageRef", b =>
                {
                    b.HasOne("MyClub.PlayUp.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
