<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="MyNet.Humanizer" Version="5.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0-preview.6.25358.103" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.0-preview.6.25358.103" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MyClub.Shared.Kernel\MyClub.Shared.Kernel.csproj" />
    </ItemGroup>
</Project>
