# Copyright (c) Stéphane ANDRE.
# Licensed under the MIT license.

# This continuous integration pipeline is triggered anytime a user pushes code to main branch.
# This pipeline create a release

name: Create Release for specific plugin

on:  
  push:
    tags:
    - 'plg.*-v*.*.*'
  workflow_dispatch:
    inputs:
      plugin:
        type: choice
        description: Name of plugin
        options: 
        - MyClub.Plugins.Scorer.Factory.Database
        - MyClub.Plugins.Scorer.Import.Database
        - MyClub.Plugins.Scorer.Import.File
        - MyClub.Plugins.Teamup.Factory.Database
        - MyClub.Plugins.Teamup.Factory.Random
        - MyClub.Plugins.Teamup.Factory.Web
        - MyClub.Plugins.Teamup.Import.Database
        - MyClub.Plugins.Teamup.Import.File
      version: 
        description: New version of plugin. If empty, use version in .csproj.
      pre_release: 
        description: Label of pre-release (pre, alpha, beta, etc...)

jobs:

  # Compute parameters
  compute_parameters:
    runs-on: ubuntu-latest
    outputs:
      build_args: ${{ steps.get_parameters.outputs.build_args }}
      plugin: ${{ steps.get_plugin.outputs.plugin }}
      full_version: ${{ steps.get_parameters.outputs.full_version }}
      version: ${{ steps.get_parameters.outputs.version }}
      pre_release: ${{ steps.get_parameters.outputs.pre_release }}

    steps:
    
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Find plugin name and version from tag
      - name: Get tag informations
        uses: olegtarasov/get-tag@v2.1.3 # https://github.com/marketplace/actions/get-tag-name
        id: get_tag
        with:
          tagRegex: plg\.(?<plugin>.*)-v(?<version>(\d|\.)*)(-(?<pre_release>.*))?

      # Return plugin name
      - name: Get plugin name
        shell: pwsh
        id: get_plugin
        run: |
          if ('${{ steps.get_tag.outputs.plugin }}' -eq '') {
            echo "plugin=${{ inputs.plugin }}" >> $Env:GITHUB_OUTPUT
          } else {
            echo "plugin=${{ steps.get_tag.outputs.plugin }}" >> $Env:GITHUB_OUTPUT
          }

      # Find version from csproj
      - uses: bbonkr/get-version-action@v1
        id: get_version
        with:
          project: src/Plugins/${{ steps.get_plugin.outputs.plugin }}/${{ steps.get_plugin.outputs.plugin }}.csproj
          show_log_message: true

      # Return version
      - name: Define used version
        shell: pwsh
        id: get_parameters
        run: |
          if ('${{ steps.get_tag.outputs.version }}' -eq '') {
            if ('${{ inputs.version }}' -eq '') {
                echo "build_args=" >> $Env:GITHUB_OUTPUT
                echo "full_version=${{ steps.get_version.outputs.version }}" >> $Env:GITHUB_OUTPUT
                echo "version=${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}.${{ steps.get_version.outputs.patch }}" >> $Env:GITHUB_OUTPUT
                echo "pre_release=${{ steps.get_version.outputs.pre-release }}" >> $Env:GITHUB_OUTPUT
            } else {
                if ('${{ inputs.pre_release }}' -eq '') {
                    echo "build_args=/p:Version=${{ inputs.version }}" >> $Env:GITHUB_OUTPUT
                    echo "full_version=${{ inputs.version }}" >> $Env:GITHUB_OUTPUT
                } else {
                    echo "build_args=/p:Version=${{ inputs.version }}-${{ inputs.pre_release }}" >> $Env:GITHUB_OUTPUT
                    echo "full_version=${{ inputs.version }}-${{ inputs.pre_release }}" >> $Env:GITHUB_OUTPUT
                }
                echo "version=${{ inputs.version }}" >> $Env:GITHUB_OUTPUT
                echo "pre_release=${{ inputs.pre_release }}" >> $Env:GITHUB_OUTPUT
            }
          } else {
            if ('${{ steps.get_tag.outputs.pre_release }}' -eq '') {
                    echo "build_args=/p:Version=${{ steps.get_tag.outputs.version}}" >> $Env:GITHUB_OUTPUT
                    echo "full_version=${{ steps.get_tag.outputs.version}}" >> $Env:GITHUB_OUTPUT
                } else {
                    echo "build_args=/p:Version=${{ steps.get_tag.outputs.version}}-${{ steps.get_tag.outputs.pre_release }}" >> $Env:GITHUB_OUTPUT
                    echo "full_version=${{ steps.get_tag.outputs.version}}-${{ steps.get_tag.outputs.pre_release }}" >> $Env:GITHUB_OUTPUT
                }
            echo "version=${{ steps.get_tag.outputs.version }}" >> $Env:GITHUB_OUTPUT
            echo "pre_release=${{ steps.get_tag.outputs.pre_release }}" >> $Env:GITHUB_OUTPUT
          }
  
  # Build project
  build:
    needs: [ compute_parameters ]
    uses: avantipoint/workflow-templates/.github/workflows/dotnet-build.yml@master # https://github.com/AvantiPoint/workflow-templates/blob/master/.github/workflows/dotnet-build.yml
    with:
      dotnet-test-logger: GitHubActions --no-build --no-restore
      build-args: ${{ needs.compute_parameters.outputs.build_args }}
      name: Build
      solution-path: .\src\Plugins\${{ needs.compute_parameters.outputs.plugin }}\${{ needs.compute_parameters.outputs.plugin }}.csproj
      artifact-name: ${{ needs.compute_parameters.outputs.plugin }}
      artifacts-path: |
              ./build/**/Release/Plugins/${{ needs.compute_parameters.outputs.plugin }}/**
              !./build/**/Release/Plugins/${{ needs.compute_parameters.outputs.plugin }}/*.xml
              !./build/**/Release/Plugins/${{ needs.compute_parameters.outputs.plugin }}/*.pdb
              
  # Create release
  release:
    runs-on: ubuntu-latest
    needs: [ compute_parameters, build ]
    env:
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    permissions:
      contents: write

    steps:
      
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Update CHANGELOG with all conventional commit from previous tag
      - name: Update CHANGELOG
        continue-on-error: true
        id: changelog
        uses: requarks/changelog-action@v1.10.1 # https://github.com/marketplace/actions/changelog-from-conventional-commits
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      # Commit changes in CHANGELOG and skip CI
      - name: Commit CHANGELOG.md
        continue-on-error: true
        uses: stefanzweifel/git-auto-commit-action@v4 # https://github.com/marketplace/actions/git-auto-commit
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md

      # Download plugin artifacts
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.compute_parameters.outputs.plugin }}
          path: ${{ needs.compute_parameters.outputs.plugin }}/
          
      # Zip plugin files
      - name: Zip artifact for deployment
        run: zip ${{ needs.compute_parameters.outputs.plugin }}_${{needs.compute_parameters.outputs.full_version}}.zip ${{ needs.compute_parameters.outputs.plugin }}/** -r

      # Get release labels
      - name: Define release parameters
        shell: pwsh
        id: compute_parameters
        run: |
          if ('${{ needs.compute_parameters.outputs.pre_release }}' -eq '') {
            echo "release_display_name=${{ needs.compute_parameters.outputs.version }}" >> $Env:GITHUB_OUTPUT
            echo "is_preview=false" >> $Env:GITHUB_OUTPUT
          } else {
            echo "is_preview=true" >> $Env:GITHUB_OUTPUT
            if ('${{ needs.compute_parameters.outputs.pre_release }}'.StartsWith('pre')) {
                echo "release_display_name=${{ needs.compute_parameters.outputs.version }} - Preview" >> $Env:GITHUB_OUTPUT
            } elseif ('${{ needs.compute_parameters.outputs.pre_release }}'.StartsWith('alpha')) {
                echo "release_display_name=${{ needs.compute_parameters.outputs.version }} - Alpha" >> $Env:GITHUB_OUTPUT
            } elseif ('${{ needs.compute_parameters.outputs.pre_release }}'.StartsWith('beta')) {
                echo "release_display_name=${{ needs.compute_parameters.outputs.version }} - Beta" >> $Env:GITHUB_OUTPUT
            }
          }

      # Create release
      - uses: ncipollo/release-action@main # https://github.com/marketplace/actions/create-release
        name: Create Release
        with:
          artifacts: ${{ needs.compute_parameters.outputs.plugin }}_${{needs.compute_parameters.outputs.full_version}}.zip
          artifactErrorsFailBuild: true
          draft: true
          generateReleaseNotes: false
          token: ${{ github.token }}
          name: ${{ needs.compute_parameters.outputs.plugin }} ${{ steps.compute_parameters.outputs.release_display_name }}
          prerelease: ${{ steps.compute_parameters.outputs.is_preview }}
          tag: ${{ needs.compute_parameters.outputs.plugin }}-v${{ steps.compute_parameters.outputs.full_version }}
          body: ${{ steps.changelog.outputs.changes }}